swagger: '2.0'
info:
  description: >-
    This is the specification which shows the mappings of urls to actions in
    ghudmusic web aplication.


    It will show you the various endpoints as well as the as the data needed
    for  consuming each endpoint with its metadata .


    It will also show you the response which will be produced by each endpoint. 


    It was built with [Swagger](http://swagger.io).you can learn more about the
    specification [here](https://swagger.io/docs/specification/what-is-swagger/)


    This `specification` will `evolve` as the project goes on with various
    updates being performed on it depending on matters arising or needs of
    project.
  version: 0.1.0
  title: Ghudmusic APi Spec
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8005'
basePath: /
tags:
  - name: authentication
    description: Authentication related links
  - name: dashboard
    description: Dashboard related links
  - name: user
    description: User Related links
schemes:
  - http
  - https
securityDefinitions:
  myCookie:
    type: apiKey
    name: Cookie
    in: header
paths:
  /auth/login:
    post:
      tags:
        - authentication
      summary: Used for login into system
      description: ''
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: formData
          name: username
          description: ''
          required: true
          type: string
        - in: formData
          name: password
          description: ''
          required: true
          type: string
      responses:
        '200':
          description: Login Succesful
          headers:
            Set-Cookie:
              type: string
              description: Contains cookie value after login
          schema:
            $ref: '#/definitions/Response'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /auth/logout:
    get:
      tags:
        - authentication
      summary: Used for logging out of the system
      description: ''
      produces:
        - application/json
      parameters:
        - in: header
          name: Cookie
          type: string
          required: true
      responses:
        '200':
          description: Logout Succesful
          schema:
            $ref: '#/definitions/Response'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /dashboard/get_links:
    get:
      deprecated: true
      security:
        - myCookie: []
      tags:
        - dashboard
      summary: For retrieving links for a user
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Category'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /dashboard/get_welcome_page:
    get:
      security:
        - myCookie: []
      tags:
        - dashboard
      summary: >-
        Data used to popuate dashboard of admin. Non admin user  dont get to see
        the chart data and stats on the right side of the page but everything
        else is the same for admin and non-admin
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DashboardData'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /users/get_profile:
    get:
      summary: for getting profile info
      tags:
        - user
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ProfileInfo'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /users/save_profile:
    post:
      summary: for saving profile info
      tags:
        - user
      description: ''
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: lname
          description: Last Name
          type: string
        - in: formData
          name: fname
          description: First Name
          type: string
        - in: formData
          name: stage_name
          description: Stage Name
          type: string
        - in: formData
          name: user_cell
          description: 'Cell #'
          type: string
        - in: formData
          name: user_email
          description: Uder Email
          type: string
        - in: formData
          name: user_facebook_link
          description: User facebook link
          type: string
        - in: formData
          name: user_twitter_link
          description: User twitter link
          type: string
        - in: formData
          name: user_youtube_link
          description: User youtube link
          type: string
        - in: formData
          name: user_instagram_link
          description: User instagram link
          type: string
      responses:
        '200':
          description: OK
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /user/reset_pass/:
    post:
      summary: for resetting pass of user
      tags:
        - user
      description: ''
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: old_password
          description: Last Name
          type: string
        - in: formData
          name: new_password
          description: New Password
          type: string
        - in: formData
          name: new_password_repeat
          description: New Password Repeated
          type: string
      responses:
        '200':
          description: OK
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  ErrorField:
    description: Error responses caused by fields
    type: object
    properties:
      field:
        type: string
        description: Field causing error
      messsage:
        type: string
        description: Description of error
  Category:
    description: Category name
    type: object
    properties:
      category:
        type: string
        description: category of links
      links:
        type: array
        items:
          $ref: '#/definitions/Slink'
  Slink:
    description: Single link
    type: object
    properties:
      id:
        type: integer
        description: id of link
      link_action:
        type: string
        description: Action segment of link
      link_allow:
        type: string
        description: will show whether link is allowed or not
        enum:
          - true
          - false
      link_category:
        type: integer
        description: category of link
      link_category_sort:
        type: integer
        description: order of link
      link_class:
        type: string
        description: class of link related to click event on client side
      link_controller:
        type: string
        description: Controller segment of link
      link_name:
        type: string
        description: Name for link
      link_type:
        type: string
        description: description of link
        enum:
          - sidebar
          - ajax
      link_parameter:
        type: string
        description: Any extra parameter for string.query string etc
  ErrorResponse:
    description: Error responses caused by other reasons
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      statusCode:
        type: integer
        format: int32
  Response:
    description: Normal responses caused by other reasons
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      statusCode:
        type: integer
        format: int32
  DataResponse:
    description: Normal responses caused by other reasons
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      statusCode:
        type: integer
        format: int32
      data_struct:
        type: object
        description: contains data which was sent in response
  ErrorDataResponse:
    description: Array of Error Responses
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      statusCode:
        type: integer
        format: int32
      error_struct:
        type: array
        items:
          $ref: '#/definitions/ErrorField'
  ArtistData:
    description: Contains artist info for dashboard
    type: object
    properties:
      count_album:
        type: integer
        format: int32
      count_tracks:
        type: integer
        format: int32
      id:
        type: integer
        format: int32
      stage_name:
        type: string
      user_email:
        type: string
      user_photo_path:
        type: string
  ChartData:
    description: Contains chart info about charts
    type: object
    properties:
      stage_name:
        type: string
      title_track:
        type: string
      song_hits:
        type: integer
        format: int32
      record_label:
        type: string
  Userdata:
    description: Contains social info about user
    type: object
    properties:
      social:
        description: Contains info about social network of user
        type: object
        properties:
          facebook:
            type: string
          twitter:
            type: string
          instagram:
            type: string
          userphone:
            type: string
          youtube:
            type: string
  DashboardData:
    description: describes dashboard data for populating index page
    type: object
    properties:
      art_data:
        type: array
        items:
          $ref: '#/definitions/ArtistData'
      chart_data:
        type: array
        items:
          $ref: '#/definitions/ChartData'
      user_data:
        type: object
        $ref: '#/definitions/Userdata'
      userlinks:
        type: array
        items:
          $ref: '#/definitions/Category'
      id:
        type: integer
      username:
        type: string
      total_artists:
        type: integer
      total_albums:
        type: integer
      total_singles:
        type: integer
  ProfileInfo:
    description: describes profile info of user
    type: object
    properties:
      fname:
        type: string
        description: first name of user
      lname:
        type: string
        description: last name of user
      stage_name:
        type: string
        description: stage name of user
      user_cell:
        type: string
        description: cell number of user
      user_email:
        type: string
        description: email/username of user
      user_facebook_link:
        type: string
        description: facebook link for user
      user_twitter_link:
        type: string
        description: twitter link for user
      user_youtube_link:
        type: string
        description: youtube link for user
      user_instagram_link:
        type: string
        description: instagram link for user
